In [1]:
import pandas as pd
import numpy as np

## BOW : Bag of Words

In [10]:
df = pd.DataFrame(
    {"text":["The cat sleeps.", "The weather is nice.", "I like coffee.", "She is reading a book."],
     "output": [1, 1, 0, 0]
    })

df

text  output
0         The cat sleeps.       1
1    The weather is nice.       1
2          I like coffee.       0
3  She is reading a book.       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [ ]:
countVectorizer = CountVectorizer()

In [12]:
bow = countVectorizer.fit_transform(df["text"]).toarray()
bow

array([[0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0]])

In [13]:
print(countVectorizer.vocabulary_)

{'the': 9, 'cat': 1, 'sleeps': 8, 'weather': 10, 'is': 3, 'nice': 5, 'like': 4, 'coffee': 2, 'she': 7, 'reading': 6, 'book': 0}


In [15]:
# new data
countVectorizer.transform(["The sun is shining."]).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0]])

## N-grams

In [ ]:
# Bi gram
countVectorizer = CountVectorizer(ngram_range=(2,2))
countVectorizer.fit_transform(df["text"]).toarray()

array([[1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 0]])

In [25]:
print(countVectorizer.vocabulary_)

{'the cat': 6, 'cat sleeps': 0, 'the weather': 7, 'weather is': 8, 'is nice': 1, 'like coffee': 3, 'she is': 5, 'is reading': 2, 'reading book': 4}


## TF-IDF

In [27]:
tfidfVectorizer = TfidfVectorizer()
tfidf = tfidfVectorizer.fit_transform(df["text"]).toarray()

In [36]:
pd.DataFrame(data=tfidf, columns=tfidfVectorizer.get_feature_names_out())

book       cat    coffee        is      like      nice   reading  \
0  0.000000  0.617614  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000  0.437791  0.000000  0.555283  0.000000   
2  0.000000  0.000000  0.707107  0.000000  0.707107  0.000000  0.000000   
3  0.525473  0.000000  0.000000  0.414289  0.000000  0.000000  0.525473   

        she    sleeps       the   weather  
0  0.000000  0.617614  0.486934  0.000000  
1  0.000000  0.000000  0.437791  0.555283  
2  0.000000  0.000000  0.000000  0.000000  
3  0.525473  0.000000  0.000000  0.000000